<?php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: POST");
header("Access-Control-Allow-Headers: Content-Type");

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Check if an image is uploaded
    if (!isset($_FILES['image']) || $_FILES['image']['error'] !== UPLOAD_ERR_OK) {
        echo json_encode(['error' => 'No image uploaded or upload error.']);
        exit;
    }
    
    // Save image temporarily
    $targetDir = "../../uploads/temp/";
    if (!is_dir($targetDir)) mkdir($targetDir, 0777, true);
    
    $fileName = 'temp_' . time() . '_' . basename($_FILES['image']['name']);
    $targetFilePath = $targetDir . $fileName;
    
    if (move_uploaded_file($_FILES['image']['tmp_name'], $targetFilePath)) {
        // Run AI Module
        $pythonScript = "../../ai_module/detect_waste.py";
        $command = escapeshellcmd("python " . escapeshellarg($pythonScript) . " " . escapeshellarg($targetFilePath));
        $output = shell_exec($command);
        
        // Delete the temporary file
        unlink($targetFilePath);
        
        echo $output; // Return the exact JSON generated by python
    } else {
        echo json_encode(['error' => 'Failed to analyze the image.']);
    }
} else {
    echo json_encode(['error' => 'Invalid request method.']);
}
?>
